version: "3.9"
services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file: mysql.env
    ports:
      - "3336:3306"
    volumes:
      - ./data:/var/lib/mysql