version: "3.9"
services:
  postgresql-db:
    image: postgres:16
    restart: always
    container_name: postgresql-db
    env_file: postgresql.env
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data